name: Readme Main (Stats)

on:
 schedule:
  - cron: "*/5 * * * *"
 workflow_dispatch:

jobs:
 main:
  runs-on: ubuntu-latest
  name: ✨ README Stats
  steps:
   - uses: actions/checkout@v2
   - name: 🎏 Fetch repo
     uses: actions/checkout@master
     with:
      fetch-depth: 1
   - name: ✨ Generate README.md
     run: |
      cd ${GITHUB_WORKSPACE}/
      npm i
      node src/index.js
   - name: 🚀 Deploy
     run: |
      if [[ "$(git status --porcelain)" != "" ]]; then
      git config user.name IgorKowalczyk
      git config user.email xxmajonezxx@gmail.com
      git add .
      git commit -m "[Bot] Update blog feed"
      git push -f
      fi
