name: Main README Updater

on:
 schedule:
  - cron: "*/5 * * * *"
 workflow_dispatch:

jobs:
 fetch-recent-blog-posts:
  name: Update README
  runs-on: ubuntu-latest
   steps:
    - name: Fetch repo
     uses: actions/checkout@master
     with:
      fetch-depth: 1
    - name: Create README.md
     run: |
      cd ${GITHUB_WORKSPACE}/
      npm i
      node src/update.js
    - name: Deploy
     run: |
      git config user.name IgorKowalczyk
      git config user.email xxmajonezxx@gmail.com
      git add .
      git commit -am "[Bot] Update README"
      git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
