name: Main README Updater

on:
 schedule:
  - cron: "*/5 * * * *"
 workflow_dispatch:

jobs:
 fetch-recent-blog-posts:
  name: Update README
  runs-on: ubuntu-latest
  steps:
   - name: Check out repository
     uses: actions/checkout@v2
   - name: Setup node
     uses: actions/setup-node@v2-beta
     with:
      node-version: "12"
   - name: Install node dependencies
     run: yarn
   - name: Run node script
     run: yarn build
   - name: Git setup
     run: git config --global user.email xxmajonezxx@gmail.com && git config --global user.name IgorKowalczyk
   - name: Git commit README.md file
     run: git diff --quiet && git diff --staged --quiet || git commit -am '[BOT] Update README' && git push
