name: Update README

on:
 schedule:
  - cron: "*/5 * * * *"
 workflow_dispatch:

jobs:
 main:
  runs-on: ubuntu-latest
  name: ✨ README Stats
  steps:
   - uses: actions/checkout@v2
   - name: 🎏 Fetch repo
     uses: actions/checkout@master
     with:
      fetch-depth: 1
   - name: ✨ Generate README.md
     run: |
      cd ${GITHUB_WORKSPACE}/
      npm i
      node src/index.js
   - name: 🚀 Deploy
     run: |
      if [[ "$(git status --porcelain)" != "" ]]; then
      git config user.name IgorKowalczyk
      git config user.email xxmajonezxx@gmail.com
      git add .
      git commit -m "[Bot] Update user stats"
      git push
      fi
 activity:
  runs-on: ubuntu-latest
  name: ✨ README Activity
  steps:
   - uses: actions/checkout@v2
   - uses: cheesits456/github-activity-readme@master
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
