on:
 schedule:
  - cron: "*/5 * * * *"
 push:
  branches:
   - master
 workflow_dispatch:

jobs:
 stats:
  runs-on: ubuntu-latest
  steps:
   - name: 🎏 Fetch repo
    uses: actions/checkout@v2
     with:
      fetch-depth: 0
   - name: ✨ Generate README.md
     uses: teoxoy/profile-readme-stats@master
     with:
      token: ${{ secrets.USER_TOKEN }}
   - name: 🚀 Push README.md
     run: |
      if [[ "$(git status --porcelain)" != "" ]]; then
      git config user.name IgorKowalczyk
      git config user.email xxmajonezxx@gmail.com
      git add .
      git commit -m "[Bot] Update user stats"
      git push
      fi
