name: Readme wakatime stats

on:
 schedule:
  - cron: "0 0 * * *"
 workflow_dispatch:

jobs:
 main:
  runs-on: ubuntu-latest
  name: ✨ README Wakatime stats
   steps:
    - uses: athul/waka-readme@master
     with:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
